model: bert
model_params:
  bert_model: sberbank-ai/ruElectra-small
  bert_hid_size: 256
  cat_size: 181
  lin_hid_size: 64

optimizer: adamw
optimizer_params:
  lr: 0.001

lr_scheduler: cosine_lr
lr_scheduler_params:
  eta_min: 0.00001
  T_max : 20

loss_fn: mse

device: cuda:0
epochs: 15
batch_size: 64
num_workers: 4
pin_memory: True
